[package]
name = "grpc-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "server"
path = "src/server.rs"

[[bin]]
name = "client"
path = "src/client.rs"

[[bin]]
name = "notifier"
path = "src/notifier.rs"

[dependencies]
tonic = "0.4"
prost = "0.7"
futures = "0.3"
futures-core = "0.3"
futures-util = "0.3"
tokio = { version = "1.0", features = ["rt-multi-thread", "macros", "sync", "time"] }
tokio-stream = "0.1"

async-stream = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
async-recursion = "1.0.2"
sha256 = "1.1.1"
chrono = "0.4.23"
redis = "0.22.3"
prometheus = { version = "0.9", features = ["process"] }
lazy_static = "1.4.0"
hyper = "0.14.24"
tower = "0.4.13"
warp = "0.3.3"
http-body = "0.4.5"

[build-dependencies]
tonic-build = "0.4"
