apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: notification-service
    version: 433fa66
  name: notification-service-433fa66
  namespace: atlas
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: notification-service
      version: 433fa66
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: notification-service
        version: 433fa66
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-type
                operator: In
                values:
                - generic-compute
      containers:
      - env:
        - name: AWS_REGION
          value: ap-south-1
        image: 701342709052.dkr.ecr.ap-south-1.amazonaws.com/notification-service:433fa66
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /health
            port: 50051
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
        name: notification-service
        ports:
        - containerPort: 50051
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 300m
            memory: 750Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30